"""empty message

Revision ID: 874bfc27037e
Revises: 
Create Date: 2021-02-16 11:28:48.640650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874bfc27037e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
