"""empty message

Revision ID: ad940d64950b
Revises: 5b311a1fb5d8
Create Date: 2021-02-17 10:38:03.138166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad940d64950b'
down_revision = '5b311a1fb5d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('todolists', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('todolists', 'name')
    # ### end Alembic commands ###
